import Head from "next/head";
import SignUp from "@/components/forms/SignUp";
import LogIn from "@/components/forms/LogIn";

export default function Home({ posts }: any) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>Index</h1>
        <SignUp />
        <LogIn />
      </main>
    </>
  );
}
